// 自动生成：weapon_fusion_suggestions.csv -> Evolution 武器草案
// 说明：status=建议 的条目是根据材料和效果的草案参数
// 提示：tier 当前为数值 2，对应 WEAPON_TIER.EVOLUTION
export const WEAPON_EVOLUTION_DRAFT = [
    {
        id: 'dark_spore_swarm',
        name: '暗孢群',
        tier: 2,
        damage: 1.4,
        interval: 45,
        speed: 6.5,
        radius: 12,
        color: '#365996',
        lifetime: 150,
        piercing: false,
        vulnerability: 0.25,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '分裂子弹 + 易伤',
        sources: ['cell', 'dark'],
        status: '现有'
    },
    {
        id: 'flame_spore_swarm',
        name: '炎孢群',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#908c55',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '分裂子弹 + 燃烧DOT',
        sources: ['cell', 'fire'],
        status: '现有'
    },
    {
        id: 'ice_shard_swarm',
        name: '冰屑群',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#10bfd5',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '分裂子弹 + 冻结',
        sources: ['cell', 'frost'],
        status: '现有'
    },
    {
        id: 'wraith_swarm',
        name: '幽群',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 10,
        radius: 12,
        color: '#1f769a',
        lifetime: 120,
        piercing: true,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '分裂子弹 + 穿透',
        sources: ['cell', 'ghost'],
        status: '现有'
    },
    {
        id: 'prism_swarm',
        name: '棱光群',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#90d9aa',
        lifetime: 120,
        piercing: false,
        blindChance: 0.5,
        blindDuration: 180,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '致盲 + 分裂子弹',
        sources: ['cell', 'light'],
        status: '现有'
    },
    {
        id: 'spark_spore_swarm',
        name: '电孢群',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#90d955',
        lifetime: 120,
        piercing: false,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '连锁闪电 + 分裂子弹',
        sources: ['cell', 'lightning'],
        status: '现有'
    },
    {
        id: 'plague',
        name: '瘟疫',
        tier: 2,
        damage: 0.6,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#6f7a66',
        lifetime: 120,
        piercing: false,
        effects: '中毒DOT + 分裂子弹',
        sources: ['cell', 'poison'],
        status: '现有'
    },
    {
        id: 'radiation_beam',
        name: '辐射射线',
        tier: 2,
        damage: 0.8,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#7CFC00',
        lifetime: 120,
        piercing: false,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '射线AOE + 分裂子弹',
        sources: ['cell', 'ray'],
        status: '现有'
    },
    {
        id: 'overgrowth',
        name: '蔓延',
        tier: 2,
        damage: 0.8,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#567c5f',
        lifetime: 120,
        piercing: false,
        overgrowthDuration: 300,
        overgrowthTriggerStacks: 3,
        overgrowthExplosionRadius: 60,
        overgrowthExplosionMultiplier: 2.5,
        effects: '蔓延叠层 + 爆发AOE',
        sources: ['cell', 'rock'],
        status: '现有'
    },
    {
        id: 'shrapnel_core',
        name: '破片核',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 7,
        radius: 12,
        color: '#70b9b5',
        lifetime: 120,
        piercing: false,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '分裂子弹 + 高伤',
        sources: ['cell', 'steel'],
        status: '现有'
    },
    {
        id: 'split_wind_swarm',
        name: '裂风群',
        tier: 2,
        damage: 0.7,
        interval: 23,
        speed: 14,
        radius: 12,
        color: '#10d955',
        lifetime: 120,
        piercing: true,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '分裂子弹 + 高速',
        sources: ['cell', 'swift'],
        status: '现有'
    },
    {
        id: 'blood_spore_swarm',
        name: '血孢群',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 7,
        radius: 12,
        color: '#565955',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        canSplit: true,
        splitCount: 2,
        splitRange: 200,
        effects: '分裂子弹 + 吸血',
        sources: ['cell', 'vampire'],
        status: '现有'
    },
    {
        id: 'dark_flame',
        name: '暗焰',
        tier: 2,
        damage: 0.5,
        interval: 45,
        speed: 6.5,
        radius: 5,
        color: '#a53341',
        lifetime: 150,
        piercing: false,
        darkFlameDuration: 1800,
        darkFlameDamagePerFrame: 0.04,
        darkFlameSpreadInterval: 60,
        darkFlameContactPadding: 6,
        darkFlameColor: '#2b153a',
        effects: '黑焰DOT + 接触传播',
        sources: ['dark', 'fire'],
        status: '现有'
    },
    {
        id: 'frost_corrosion',
        name: '怨灵',
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 6.5,
        radius: 5,
        color: '#2666c1',
        lifetime: 150,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        effects: '冻结 + 诅咒',
        sources: ['dark', 'frost'],
        status: '现有'
    },
    {
        id: 'shadow_wraith',
        name: '恶灵',
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 8.5,
        radius: 5,
        color: '#351d86',
        lifetime: 150,
        piercing: true,
        effects: '穿透 + 诅咒',
        sources: ['dark', 'ghost'],
        status: '现有'
    },
    {
        id: 'eclipse',
        name: '闪烁',
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 6.5,
        radius: 5,
        color: '#a58096',
        lifetime: 150,
        piercing: false,
        fullScreenDamage: true,
        effects: '全屏伤害',
        sources: ['dark', 'light'],
        status: '现有'
    },
    {
        id: 'void_thunder',
        name: '虚雷',
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 6.5,
        radius: 12,
        color: '#a58041',
        lifetime: 150,
        piercing: false,
        vulnerability: 0.25,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '连锁闪电 + 易伤',
        sources: ['dark', 'lightning'],
        status: '现有'
    },
    {
        id: 'void_beam',
        name: '虚空射线',
        tier: 2,
        damage: 1.4,
        interval: 45,
        speed: 6.5,
        radius: 12,
        color: '#a55341',
        lifetime: 150,
        piercing: false,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '射线AOE + 诅咒',
        sources: ['dark', 'ray'],
        status: '现有'
    },
    {
        id: 'cursed_stone',
        name: '暗蚀地带',
        tier: 2,
        damage: 1.4,
        interval: 45,
        speed: 6.5,
        radius: 12,
        color: '#6b234b',
        lifetime: 150,
        piercing: false,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '圆形AOE + 诅咒',
        sources: ['dark', 'rock'],
        status: '现有'
    },
    {
        id: 'dark_steel',
        name: '手里剑',
        tier: 2,
        damage: 1,
        interval: 90,
        speed: 5.5,
        radius: 6,
        color: '#8660a1',
        lifetime: 150,
        piercing: false,
        canSplit: true,
        splitCount: 5,
        splitRange: 200,
        splitDamageMultiplier: 0.2,
        effects: '分裂小子弹',
        sources: ['dark', 'steel'],
        status: '现有'
    },
    {
        id: 'night_blade',
        name: '夜刃',
        tier: 2,
        damage: 1.3,
        interval: 40,
        speed: 8.5,
        radius: 5,
        color: '#268041',
        lifetime: 150,
        piercing: true,
        vulnerability: 0.25,
        effects: '穿透 + 易伤',
        sources: ['dark', 'swift'],
        status: '现有'
    },
    {
        id: 'soul_drain',
        name: '血咒',
        tier: 2,
        damage: 1.5,
        interval: 45,
        speed: 5.5,
        radius: 5,
        color: '#6b0041',
        lifetime: 150,
        piercing: false,
        abyssSacrificeDuration: 600,
        abyssSacrificeHeal: 2,
        effects: '诅咒 + 海渊献祭',
        sources: ['dark', 'vampire'],
        status: '现有'
    },
    {
        id: 'abyss_wraith',
        name: '渊灵',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 10,
        radius: 4,
        color: '#3a4b6a',
        lifetime: 120,
        piercing: true,
        abyssSacrificeDuration: 600,
        abyssSacrificeHeal: 2,
        effects: '穿透 + 海渊献祭',
        sources: ['ghost', 'vampire'],
        status: '现有'
    },
    {
        id: 'frostfire',
        name: '燃霜',
        tier: 2,
        damage: 0.5,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#00ccff',
        lifetime: 120,
        piercing: false,
        burnDuration: 1200,
        burnDamagePerFrame: 0.16666666666666666,
        burnColor: '#00ccff',
        vulnerability: 0.25,
        effects: '燃烧DOT + 易伤',
        sources: ['frost', 'fire'],
        status: '现有'
    },
    {
        id: 'ghost_fire',
        name: '鬼火',
        tier: 2,
        damage: 0.5,
        interval: 30,
        speed: 10,
        radius: 4,
        color: '#8f5045',
        lifetime: 120,
        piercing: true,
        darkFlameDuration: 1800,
        darkFlameDamagePerFrame: 0.04,
        darkFlameSpreadInterval: 60,
        darkFlameContactPadding: 6,
        darkFlameColor: '#2b153a',
        effects: '穿透 + 黑焰',
        sources: ['fire', 'ghost'],
        status: '现有'
    },
    {
        id: 'dazzle_flame',
        name: '眩光焰',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#ffb355',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '燃烧DOT + 致盲',
        sources: ['fire', 'light'],
        status: '现有'
    },
    {
        id: 'plasma_chain',
        name: '等离火链',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#ffb300',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '燃烧DOT + 连锁闪电',
        sources: ['fire', 'lightning'],
        status: '现有'
    },
    {
        id: 'toxic_flame',
        name: '硫磺',
        tier: 2,
        damage: 0.75,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#80b300',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        effects: '燃烧DOT + 中毒DOT',
        sources: ['fire', 'poison'],
        status: '现有'
    },
    {
        id: 'high_temperature_ray',
        name: '高温射线',
        tier: 2,
        damage: 3.5,
        interval: 45,
        speed: 8,
        radius: 6,
        color: '#ff8600',
        lifetime: 120,
        piercing: false,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '射线AOE',
        sources: ['fire', 'ray'],
        status: '现有'
    },
    {
        id: 'lava',
        name: '熔岩',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 6,
        radius: 14,
        color: '#c5560a',
        lifetime: 240,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        effects: '圆形AOE + 燃烧DOT',
        sources: ['fire', 'rock'],
        status: '现有'
    },
    {
        id: 'bomb',
        name: '炸弹',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 8,
        radius: 6,
        color: '#ff4500',
        lifetime: 120,
        piercing: false,
        explosionRadius: 100,
        explosionDamage: 2,
        effects: '爆炸AOE',
        sources: ['steel', 'fire'],
        status: '现有'
    },
    {
        id: 'inferno',
        name: '炼狱',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 10,
        radius: 12,
        color: '#cc0000',
        lifetime: 120,
        piercing: true,
        burnDuration: 300,
        burnDamagePerFrame: 0.08333333333333333,
        effects: '穿透 + 燃烧DOT',
        sources: ['swift', 'fire'],
        status: '现有'
    },
    {
        id: 'blood_flame',
        name: '血焰',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 7,
        radius: 4,
        color: '#c53300',
        lifetime: 120,
        piercing: false,
        burnDuration: 300,
        burnDamagePerFrame: 0.083333,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        effects: '燃烧DOT + 吸血',
        sources: ['fire', 'vampire'],
        status: '现有'
    },
    {
        id: 'frost_wraith',
        name: '霜灵',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 10,
        radius: 4,
        color: '#0f83c5',
        lifetime: 120,
        piercing: true,
        freezeChance: 0.3,
        freezeDuration: 120,
        effects: '穿透 + 冻结',
        sources: ['frost', 'ghost'],
        status: '现有'
    },
    {
        id: 'white_halo',
        name: '白晕',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#80e6d5',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '冻结 + 致盲',
        sources: ['frost', 'light'],
        status: '现有'
    },
    {
        id: 'ice_chain',
        name: '冰电链',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#80e680',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '冻结 + 连锁闪电',
        sources: ['frost', 'lightning'],
        status: '现有'
    },
    {
        id: 'ice_toxin',
        name: '冰毒',
        tier: 2,
        damage: 0.75,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#00e680',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        effects: '冻结 + 中毒DOT',
        sources: ['frost', 'poison'],
        status: '现有'
    },
    {
        id: 'cold_beam',
        name: '寒束',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#80b980',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '射线AOE + 冻结',
        sources: ['frost', 'ray'],
        status: '现有'
    },
    {
        id: 'glacier',
        name: '冰川',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 6,
        radius: 14,
        color: '#468989',
        lifetime: 240,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        effects: '圆形AOE + 冻结',
        sources: ['frost', 'rock'],
        status: '现有'
    },
    {
        id: 'ice_spike',
        name: '冰锥',
        tier: 2,
        damage: 2.4,
        interval: 80,
        speed: 7,
        radius: 6,
        color: '#60c6e0',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        effects: '冻结 + 高伤',
        sources: ['frost', 'steel'],
        status: '现有'
    },
    {
        id: 'blizzard',
        name: '暴风雪',
        tier: 2,
        damage: 0.75,
        interval: 20,
        speed: 12,
        radius: 12,
        color: '#00ccff',
        lifetime: 120,
        piercing: true,
        freezeChance: 0.5,
        freezeDuration: 180,
        vulnerability: 0.25,
        effects: '穿透 + 冻结 + 易伤',
        sources: ['swift', 'frost'],
        status: '现有'
    },
    {
        id: 'frost_leech',
        name: '寒魄吸',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 7,
        radius: 4,
        color: '#466680',
        lifetime: 120,
        piercing: false,
        freezeChance: 0.3,
        freezeDuration: 120,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        effects: '冻结 + 吸血',
        sources: ['frost', 'vampire'],
        status: '现有'
    },
    {
        id: 'holy_wisp',
        name: '圣灵',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 10,
        radius: 4,
        color: '#8f9d9a',
        lifetime: 120,
        piercing: true,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '致盲 + 穿透',
        sources: ['ghost', 'light'],
        status: '现有'
    },
    {
        id: 'electric_soul',
        name: '电魂',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 10,
        radius: 12,
        color: '#8f9d45',
        lifetime: 120,
        piercing: true,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '连锁闪电 + 穿透',
        sources: ['ghost', 'lightning'],
        status: '现有'
    },
    {
        id: 'nether_stone',
        name: '幽冥石',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 6,
        radius: 14,
        color: '#55404f',
        lifetime: 240,
        piercing: true,
        effects: '圆形AOE + 穿透',
        sources: ['ghost', 'rock'],
        status: '现有'
    },
    {
        id: 'phantom_blade',
        name: '幽刃',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 9,
        radius: 6,
        color: '#6f7da5',
        lifetime: 120,
        piercing: true,
        effects: '穿透 + 高伤',
        sources: ['ghost', 'steel'],
        status: '现有'
    },
    {
        id: 'shadow_rush',
        name: '影疾',
        tier: 2,
        damage: 0.8,
        interval: 23,
        speed: 14,
        radius: 4,
        color: '#0f9d45',
        lifetime: 120,
        piercing: true,
        effects: '穿透 + 高速',
        sources: ['ghost', 'swift'],
        status: '现有'
    },
    {
        id: 'blood_wraith',
        name: '血影',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 9,
        radius: 4,
        color: '#551d45',
        lifetime: 120,
        piercing: true,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        effects: '穿透 + 吸血',
        sources: ['ghost', 'vampire'],
        status: '现有'
    },
    {
        id: 'radiant_arc',
        name: '闪耀电弧',
        tier: 2,
        damage: 1,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#ffff55',
        lifetime: 120,
        piercing: false,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '连锁闪电 + 致盲',
        sources: ['light', 'lightning'],
        status: '现有'
    },
    {
        id: 'toxic_daze',
        name: '毒眩',
        tier: 2,
        damage: 0.75,
        interval: 30,
        speed: 8,
        radius: 4,
        color: '#80ff55',
        lifetime: 120,
        piercing: false,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '中毒DOT + 致盲',
        sources: ['light', 'poison'],
        status: '现有'
    },
    {
        id: 'sun_lance',
        name: '日光矛',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#ffd255',
        lifetime: 120,
        piercing: false,
        blindChance: 0.5,
        blindDuration: 180,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '致盲 + 射线AOE',
        sources: ['light', 'ray'],
        status: '现有'
    },
    {
        id: 'crystal_glow',
        name: '晶耀',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 6,
        radius: 14,
        color: '#c5a25f',
        lifetime: 240,
        piercing: false,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '致盲 + 圆形AOE',
        sources: ['light', 'rock'],
        status: '现有'
    },
    {
        id: 'holy_hammer',
        name: '圣锤',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 7,
        radius: 6,
        color: '#e0e0b5',
        lifetime: 120,
        piercing: false,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '高伤 + 致盲',
        sources: ['light', 'steel'],
        status: '现有'
    },
    {
        id: 'flash_strike',
        name: '闪袭',
        tier: 2,
        damage: 0.8,
        interval: 25,
        speed: 10,
        radius: 4,
        color: '#80ff55',
        lifetime: 120,
        piercing: true,
        blindChance: 0.5,
        blindDuration: 180,
        effects: '穿透 + 致盲',
        sources: ['light', 'swift'],
        status: '现有'
    },
    {
        id: 'holy_heal',
        name: '圣愈',
        tier: 2,
        damage: 0.1,
        interval: 30,
        speed: 7,
        radius: 4,
        color: '#c58055',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.21,
        lifeStealAmount: 1,
        effects: '吸血',
        sources: ['light', 'vampire'],
        status: '现有'
    },
    {
        id: 'venom_arc',
        name: '毒电链',
        tier: 2,
        damage: 0.75,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#80ff00',
        lifetime: 120,
        piercing: false,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '中毒DOT + 连锁闪电',
        sources: ['lightning', 'poison'],
        status: '现有'
    },
    {
        id: 'ion_beam',
        name: '离子束',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#ffd200',
        lifetime: 120,
        piercing: false,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '连锁闪电 + 射线AOE',
        sources: ['lightning', 'ray'],
        status: '现有'
    },
    {
        id: 'thunder_grit',
        name: '雷砾',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 6,
        radius: 14,
        color: '#c5a20a',
        lifetime: 240,
        piercing: false,
        effects: '连锁闪电 + 圆形AOE',
        sources: ['lightning', 'rock'],
        status: '现有'
    },
    {
        id: 'mag_rail',
        name: '避雷针',
        tier: 2,
        damage: 0.8,
        interval: 90,
        speed: 7,
        radius: 12,
        color: '#e0e060',
        lifetime: 120,
        piercing: false,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        lightningRodDuration: 180,
        lightningRodInterval: 60,
        lightningRodStrikes: 3,
        effects: '连锁闪电 + 引雷',
        sources: ['lightning', 'steel'],
        status: '现有'
    },
    {
        id: 'storm',
        name: '风暴',
        tier: 2,
        damage: 0.75,
        interval: 20,
        speed: 12,
        radius: 12,
        color: '#ffff00',
        lifetime: 120,
        piercing: true,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '穿透 + 连锁闪电',
        sources: ['swift', 'lightning'],
        status: '现有'
    },
    {
        id: 'leech_arc',
        name: '雷汲脉冲',
        tier: 2,
        damage: 0.5,
        interval: 30,
        speed: 7,
        radius: 4,
        color: '#c58000',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        chainCount: 3,
        chainRange: 150,
        chainCooldown: 10,
        effects: '连锁闪电 + 吸血',
        sources: ['lightning', 'vampire'],
        status: '现有'
    },
    {
        id: 'swamp',
        name: '沼泽',
        tier: 2,
        damage: 0.65,
        interval: 30,
        speed: 6,
        radius: 14,
        color: '#46a20a',
        lifetime: 240,
        piercing: false,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        effects: '中毒DOT + 圆形AOE',
        sources: ['poison', 'rock'],
        status: '现有'
    },
    {
        id: 'toxic_spike',
        name: '毒钉',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 7,
        radius: 6,
        color: '#60e060',
        lifetime: 120,
        piercing: false,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        effects: '高伤 + 中毒DOT',
        sources: ['poison', 'steel'],
        status: '现有'
    },
    {
        id: 'poison_mist',
        name: '毒雾',
        tier: 2,
        damage: 0.75,
        interval: 30,
        speed: 10,
        radius: 12,
        color: '#00ff00',
        lifetime: 120,
        piercing: true,
        poisonDuration: 900,
        poisonDamagePerStack: 0.05,
        effects: '穿透 + 中毒DOT',
        sources: ['swift', 'poison'],
        status: '现有'
    },
    {
        id: 'ley_beam',
        name: '地脉束',
        tier: 2,
        damage: 0.8,
        interval: 30,
        speed: 8,
        radius: 12,
        color: '#c5750a',
        lifetime: 120,
        piercing: false,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '射线AOE + 圆形AOE',
        sources: ['ray', 'rock'],
        status: '现有'
    },
    {
        id: 'rail_beam',
        name: '轨道束',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 7,
        radius: 12,
        color: '#e0b360',
        lifetime: 120,
        piercing: false,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '射线AOE + 高伤',
        sources: ['ray', 'steel'],
        status: '现有'
    },
    {
        id: 'rapid_beam',
        name: '疾光束',
        tier: 2,
        damage: 0.7,
        interval: 23,
        speed: 14,
        radius: 12,
        color: '#80d200',
        lifetime: 120,
        piercing: true,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '射线AOE + 高速',
        sources: ['ray', 'swift'],
        status: '现有'
    },
    {
        id: 'blood_beam',
        name: '血束',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 7,
        radius: 12,
        color: '#c55300',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        rayRange: 300,
        rayLength: 600,
        rayWidth: 10,
        effects: '射线AOE + 吸血',
        sources: ['ray', 'vampire'],
        status: '现有'
    },
    {
        id: 'rift_hammer',
        name: '裂地锤',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 6,
        radius: 14,
        color: '#a6836a',
        lifetime: 240,
        piercing: false,
        effects: '高伤 + 圆形AOE',
        sources: ['rock', 'steel'],
        status: '现有'
    },
    {
        id: 'sandstorm',
        name: '砂暴',
        tier: 2,
        damage: 0.7,
        interval: 25,
        speed: 10,
        radius: 12,
        color: '#46a20a',
        lifetime: 120,
        piercing: true,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '穿透 + 圆形AOE',
        sources: ['rock', 'swift'],
        status: '现有'
    },
    {
        id: 'blood_quake',
        name: '血震',
        tier: 2,
        damage: 0.9,
        interval: 30,
        speed: 7,
        radius: 12,
        color: '#8b230a',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        aoeRadius: 80,
        aoeDamage: 0.8,
        effects: '圆形AOE + 吸血',
        sources: ['rock', 'vampire'],
        status: '现有'
    },
    {
        id: 'rapid_lance',
        name: '疾枪',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 9,
        radius: 6,
        color: '#60e060',
        lifetime: 120,
        piercing: true,
        effects: '穿透 + 高伤',
        sources: ['steel', 'swift'],
        status: '现有'
    },
    {
        id: 'blood_hammer',
        name: '血槌',
        tier: 2,
        damage: 3,
        interval: 90,
        speed: 6,
        radius: 6,
        color: '#a66060',
        lifetime: 120,
        piercing: false,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        effects: '高伤 + 吸血',
        sources: ['steel', 'vampire'],
        status: '现有'
    },
    {
        id: 'swift_leech',
        name: '迅吸',
        tier: 2,
        damage: 0.8,
        interval: 25,
        speed: 9,
        radius: 4,
        color: '#468000',
        lifetime: 120,
        piercing: true,
        lifeStealChance: 0.06,
        lifeStealAmount: 1,
        effects: '穿透 + 吸血',
        sources: ['swift', 'vampire'],
        status: '现有'
    },
];
